### PR TITLE
fix: subuser works

### PR DESCRIPTION
**Pull request by timja**
Fixes https://github.com/Trois-Six/terraform-provider-sendgrid/issues/4

I'm no expert at golang, so suggested improvements welcomed

This adds:
* create, delete of sub users work
* sendgrid very aggressively rate limits creation and deletion of sub users, this adds back off, tested with 10 users in terraform code
* api_key can now create in a sub user without needing a new instance of the provider 

cc @Trois-Six

### CODE REVIEW

**Review by luigibk — APPROVED** [review]

**Review by Trois-Six — APPROVED** [review]
LGTM. I will modify after merge some things, but I merge this for now.

**Comment by timja** [comment]
Thanks! We will check it out tomorrow UTC

**Comment by Trois-Six** [comment]
I did a lot of modifications after your PR, but I don't have subUsers...

**Comment by timja** [comment]
@Trois-Six no idea what the release process is like to the terraform portal but it seems to be not available yet?

> Error: Failed to query available provider packages
>
> Could not retrieve the list of available versions for provider
> trois-six/sendgrid: no available releases match the given constraints 0.1.4

**Comment by timja** [comment]
@Trois-Six Your changes cause a crash:

```
2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid: panic: runtime error: index out of range [0] with length 0
2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid:
2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid: goroutine 52 [running]:
2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid: github.com/trois-six/terraform-provider-sendgrid/sdk.(*Client).CreateSubuser(0xc0005f00c0, 0xc0007687d0, 0xc, 0xc00077e760, 0x11, 0xc00
077e780, 0x14, 0xc0006f4850, 0x1, 0x1, ...)
2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid:    /Users/timja/projects/go/src/github.com/Trois-Six/terraform-provider-sendgrid/sdk/subuser.go:90 +0x3b9
2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid: github.com/trois-six/terraform-provider-sendgrid/sendgrid.retrySubUserCreateClient.func1(0x1085870)
2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid:    /Users/timja/projects/go/src/github.com/Trois-Six/terraform-provider-sendgrid/sendgrid/resource_sendgrid_subuser.go:130 +0x8d
2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid: github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.RetryContext.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid:    /Users/timja/projects/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/resource/wait.go:27 +0x5e
2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid: github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1(0xc0006bc5a0, 0xc0003f8930, 0
xc0000b62a0, 0xc00030cc00, 0xc000608038, 0xc000608030)
2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid:    /Users/timja/projects/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/resource/state.go:110 +0x329
2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid: created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid:    /Users/timja/projects/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/resource/state.go:83 +0x1c5
2021-03-10T08:02:37.832Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
```

I can look at it later if you don't have time

**Comment by Trois-Six** [comment]
> @Trois-Six no idea what the release process is like to the terraform portal but it seems to be not available yet?
> 
> > Error: Failed to query available provider packages
> > Could not retrieve the list of available versions for provider
> > trois-six/sendgrid: no available releases match the given constraints 0.1.4

Some artifacts failed to upload. It's ok now.

**Comment by Trois-Six** [comment]
> @Trois-Six Your changes cause a crash:
> 
> ```
> 2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid: panic: runtime error: index out of range [0] with length 0
> 2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid:
> 2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid: goroutine 52 [running]:
> 2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid: github.com/trois-six/terraform-provider-sendgrid/sdk.(*Client).CreateSubuser(0xc0005f00c0, 0xc0007687d0, 0xc, 0xc00077e760, 0x11, 0xc00
> 077e780, 0x14, 0xc0006f4850, 0x1, 0x1, ...)
> 2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid:    /Users/timja/projects/go/src/github.com/Trois-Six/terraform-provider-sendgrid/sdk/subuser.go:90 +0x3b9
> 2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid: github.com/trois-six/terraform-provider-sendgrid/sendgrid.retrySubUserCreateClient.func1(0x1085870)
> 2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid:    /Users/timja/projects/go/src/github.com/Trois-Six/terraform-provider-sendgrid/sendgrid/resource_sendgrid_subuser.go:130 +0x8d
> 2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid: github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.RetryContext.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
> 2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid:    /Users/timja/projects/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/resource/wait.go:27 +0x5e
> 2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid: github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1(0xc0006bc5a0, 0xc0003f8930, 0
> xc0000b62a0, 0xc00030cc00, 0xc000608038, 0xc000608030)
> 2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid:    /Users/timja/projects/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/resource/state.go:110 +0x329
> 2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid: created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
> 2021-03-10T08:02:37.829Z [DEBUG] plugin.terraform-provider-sendgrid:    /Users/timja/projects/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/resource/state.go:83 +0x1c5
> 2021-03-10T08:02:37.832Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
> ```
> 
> I can look at it later if you don't have time

thx, I don't have much time yes...

**Comment by Trois-Six** [comment]
or even https://github.com/Trois-Six/terraform-provider-sendgrid/commit/a952286cec528a3effbebcbfdb5f7cf0a581ca66.

**Comment by Trois-Six** [comment]
I did another modification to try to handle all edge cases: https://github.com/Trois-Six/terraform-provider-sendgrid/commit/c30a589cc6a08b6f5d7bde429571027413fd25a1.

**Comment by timja** [comment]
Second commit (https://github.com/Trois-Six/terraform-provider-sendgrid/commit/c30a589cc6a08b6f5d7bde429571027413fd25a1):

```
Error: failed parsing subUsers: json: cannot unmarshal object into Go value of type []sendgrid.SubUser

  on main.tf line 36, in resource "sendgrid_subuser" "subuser-count":
  36: resource "sendgrid_subuser" "subuser-count" {


```

**Comment by Trois-Six** [comment]
ok... it seems I will have to create a test environment.

**Pull request merged**
